version: '2'
services:

  server:
    build: ./app
    ports:
      - "9000:9000"
    networks:
      - ethereal-network

  redis:
    image: redis
    ports:
     - "6379"
    networks:
      - ethereal-network

networks:
  ethereal-network:
    driver: bridge